module.exports = {
	extends: ['eslint:recommended'],
	rules: {
		'array-callback-return': ['error', { checkForEach: true }],
		'constructor-super': 'error',
		'for-direction': 'error',
		'getter-return': 'error',
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': ['error', 'always'],
		'no-const-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': 'error',
		'no-constructor-return': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-dupe-args': 'error',
		'no-dupe-class-members': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-duplicate-imports': ['error', { includeExports: true }],
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-ex-assign': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-import-assign': 'error',
		'no-inner-declarations': ['error', 'both'],
		'no-invalid-regexp': [
			'error',
			{ allowConstructorFlags: ['d', 'g', 'i', 'm', 's', 'u', 'v', 'y'] },
		],
		'no-irregular-whitespace': [
			'error',
			{
				skipStrings: true,
				skipComments: true,
				skipRegExps: true,
				skipTemplates: true,
				skipJSXText: true,
			},
		],
		'no-loss-of-precision': 'error',
		'no-misleading-character-class': 'error',
		'no-new-native-nonconstructor': 'error',
		'no-new-symbol': 'error',
		'no-obj-calls': 'error',
		'no-promise-executor-return': 'error',
		'no-prototype-builtins': 'error',
		'no-self-assign': 'error',
		'no-self-compare': 'error',
		'no-setter-return': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-this-before-super': 'error',
		'no-undef': 'error',
		'no-unexpected-multiline': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unreachable': 'error',
		'no-unreachable-loop': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'no-unsafe-optional-chaining': 'error',
		'no-unused-private-class-members': 'error',
		'no-unused-vars': [
			'error',
			{
				vars: 'all',
				args: 'after-used',
				caughtErrors: 'all',
				ignoreRestSiblings: true,
			},
		],
		'no-use-before-define': [
			'error',
			{
				functions: true,
				classes: true,
				variables: true,
			},
		],
		'no-useless-backreference': 'error',
		'require-atomic-updates': 'off',
		'use-isnan': [
			'error',
			{
				enforceForSwitchCase: true,
				enforceForIndexOf: true,
			},
		],
		'valid-typeof': ['error', { requireStringLiterals: true }],
		'accessor-pairs': 'error',
		'arrow-body-style': 'off',
		'block-scoped-var': 'error',
		camelcase: [
			'error',
			{
				properties: 'always',
				ignoreDestructuring: true,
				ignoreImports: true,
				ignoreGlobals: true,
			},
		],
		'capitalized-comments': 'off',
		'class-methods-use-this': 'off',
		complexity: 'off',
		'consistent-return': 'off',
		'consistent-this': 'off',
		curly: ['error', 'multi-line'],
		'default-case': 'off',
		'default-case-last': 'error',
		'default-param-last': 'error',
		'dot-notation': 'off',
		eqeqeq: ['error', 'always'],
		'func-name-matching': 'off',
		'func-names': ['error', 'never'],
		'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
		'grouped-accessor-pairs': ['error', 'getBeforeSet'],
		'guard-for-in': 'off',
		'id-denylist': 'off',
		'id-length': 'off',
		'id-match': 'off',
		'init-declarations': 'off',
		'logical-assignment-operators': 'off',
		'max-classes-per-file': 'off',
		'max-depth': 'off',
		'max-lines': 'off',
		'max-lines-per-function': 'off',
		'max-nested-callbacks': 'off',
		'max-params': 'off',
		'max-statements': 'off',
		'multiline-comment-style': 'off',
		'new-cap': 'error',
		'no-alert': 'error',
		'no-array-constructor': 'off',
		'no-bitwise': 'off',
		'no-caller': 'off',
		'no-case-declarations': 'error',
		'no-console': 'warn',
		'no-continue': 'off',
		'no-delete-var': 'error',
		'no-div-regex': 'off',
		'no-else-return': 'error',
		'no-empty': 'error',
		'no-empty-function': 'error',
		'no-empty-static-block': 'error',
		'no-eq-null': 'off',
		'no-eval': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': 'error',
		'no-extra-label': 'error',
		'no-global-assign': 'error',
		'no-implicit-coercion': ['error', { disallowTemplateShorthand: true }],
		'no-implicit-globals': 'error',
		'no-implied-eval': 'error',
		'no-invalid-this': 'error',
		'no-iterator': 'error',
		'no-label-var': 'error',
		'no-labels': 'off',
		'no-lone-blocks': 'error',
		'no-lonely-if': 'off',
		'no-loop-func': 'error',
		'no-magic-numbers': 'off',
		'no-multi-assign': 'error',
		'no-multi-str': 'error',
		'no-negated-condition': 'error',
		'no-nested-ternary': 'error',
		'no-new': 'off',
		'no-new-func': 'error',
		'no-new-wrappers': 'error',
		'no-nonoctal-decimal-escape': 'error',
		'no-object-constructor': 'error',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'off',
		'no-plusplus': 'off',
		'no-proto': 'error',
		'no-redeclare': 'error',
		'no-regex-spaces': 'error',
		'no-restricted-exports': 'off',
		'no-restricted-globals': 'off',
		'no-restricted-imports': 'off',
		'no-restricted-properties': 'off',
		'no-restricted-syntax': 'off',
		'no-return-assign': ['error', 'except-parens'],
		'no-script-url': 'error',
		'no-sequences': 'error',
		'no-shadow': ['error', { hoist: 'all' }],
		'no-shadow-restricted-names': 'error',
		'no-ternary': 'off',
		'no-throw-literal': 'error',
		'no-undef-init': 'off',
		'no-undefined': 'off',
		'no-underscore-dangle': 'off',
		'no-unneeded-ternary': 'error',
		'no-unused-expressions': [
			'error',
			{ allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true },
		],
		'no-unused-labels': 'error',
		'no-useless-call': 'error',
		'no-useless-catch': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-concat': 'error',
		'no-useless-constructor': 'error',
		'no-useless-escape': 'error',
		'no-useless-rename': 'error',
		'no-useless-return': 'error',
		'no-var': 'error',
		'no-void': 'error',
		'no-warning-comments': 'off',
		'no-with': 'error',
		'object-shorthand': 'off',
		'one-var': ['error', 'never'],
		'operator-assignment': 'off',
		'prefer-arrow-callback': 'off',
		'prefer-const': [
			'error',
			{
				destructuring: 'all',
				ignoreReadBeforeAssign: true,
			},
		],
		'prefer-destructuring': 'off',
		'prefer-exponentiation-operator': 'error',
		'prefer-named-capture-group': 'error',
		'prefer-numeric-literals': 'error',
		'prefer-object-has-own': 'error',
		'prefer-object-spread': 'error',
		'prefer-promise-reject-errors': 'error',
		'prefer-regex-literals': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		radix: ['error', 'as-needed'],
		'require-await': 'error',
		'require-unicode-regexp': 'off',
		'require-yield': 'error',
		'sort-imports': 'off',
		'sort-keys': 'off',
		'sort-vars': 'off',
		strict: 'off',
		'symbol-description': 'off',
		'vars-on-top': 'off',
		yoda: ['error', 'never'],
		'line-comment-position': 'off',
		'unicode-bom': 'off',
	},
};
