// https://typescript-eslint.io/rules
module.exports = {
	overrides: [
		{
			files: ['./vite.config.ts'],
			parserOptions: {
				project: '../tsconfig.node.json',
				tsconfigRootDir: __dirname,
			},
		},
		{
			plugins: ['@typescript-eslint'],
			extends: [
				'plugin:@typescript-eslint/strict-type-checked',
				'plugin:@typescript-eslint/stylistic-type-checked',
			],
			files: ['./src/**/*.{ts,cts,mts,tsx}'],
			parserOptions: {
				project: '../tsconfig.app.json',
				tsconfigRootDir: __dirname,
			},
			rules: {
				'@typescript-eslint/no-dynamic-delete': 'off',

				// Extend core eslint rules
				'default-param-last': 'off',
				'@typescript-eslint/default-param-last': 'error',
				'no-loop-func': 'off',
				'@typescript-eslint/no-loop-func': 'error',
				'no-shadow': 'off',
				'@typescript-eslint/no-shadow': [
					'error',
					{
						ignoreTypeValueShadow: true,
						ignoreFunctionTypeParameterNameValueShadow: true,
					},
				],
				'no-unused-expressions': 'off',
				'@typescript-eslint/no-unused-expressions': [
					'error',
					{
						allowShortCircuit: true,
						allowTernary: true,
						allowTaggedTemplates: true,
					},
				],
				'no-use-before-define': 'off',
				'@typescript-eslint/no-use-before-define': ['error', { ignoreTypeReferences: false }],

				// '@typescript-eslint/adjacent-overload-signatures': 'error',
				// '@typescript-eslint/array-type': 'off',
				// '@typescript-eslint/await-thenable': 'error',
				// '@typescript-eslint/ban-ts-comment': 'error',
				// '@typescript-eslint/ban-tslint-comment': 'off',
				// '@typescript-eslint/ban-types': 'error',
				// '@typescript-eslint/class-literal-property-style': 'off',
				// '@typescript-eslint/class-methods-use-this': 'off',
				// '@typescript-eslint/consistent-generic-constructors': 'off',
				// '@typescript-eslint/consistent-indexed-object-style': 'off',
				// '@typescript-eslint/consistent-type-assertions': 'off',
				// '@typescript-eslint/consistent-type-definitions': 'off',
				// '@typescript-eslint/consistent-type-exports': 'off',
				// '@typescript-eslint/consistent-type-imports': 'off',
				// '@typescript-eslint/default-param-last': 'off',
				// '@typescript-eslint/dot-notation': 'off',
				// '@typescript-eslint/explicit-function-return-type': 'off',
				// '@typescript-eslint/explicit-member-accessibility': 'off',
				// '@typescript-eslint/explicit-module-boundary-types': 'off',
				// '@typescript-eslint/init-declarations': 'off',
				// '@typescript-eslint/max-params': 'off',
				// '@typescript-eslint/member-ordering': 'off',
				// '@typescript-eslint/method-signature-style': 'off',
				// '@typescript-eslint/naming-convention': 'off',
				// '@typescript-eslint/no-array-constructor': 'error',
				// '@typescript-eslint/no-base-to-string': 'error',
				// '@typescript-eslint/no-confusing-non-null-assertion': 'off',
				// '@typescript-eslint/no-confusing-void-expression': 'error',
				// '@typescript-eslint/no-dupe-class-members': 'off',
				// '@typescript-eslint/no-duplicate-enum-values': 'error',
				// '@typescript-eslint/no-duplicate-type-constituents': 'error',
				// '@typescript-eslint/no-dynamic-delete': 'error',
				// '@typescript-eslint/no-empty-function': 'off',
				// '@typescript-eslint/no-empty-interface': 'off',
				// '@typescript-eslint/no-explicit-any': 'error',
				// '@typescript-eslint/no-extra-non-null-assertion': 'error',
				// '@typescript-eslint/no-extraneous-class': 'error',
				// '@typescript-eslint/no-floating-promises': 'error',
				// '@typescript-eslint/no-for-in-array': 'error',
				// '@typescript-eslint/no-implied-eval': 'error',
				// '@typescript-eslint/no-import-type-side-effects': 'off',
				// '@typescript-eslint/no-inferrable-types': 'off',
				// '@typescript-eslint/no-invalid-this': 'off',
				// '@typescript-eslint/no-invalid-void-type': 'error',
				// '@typescript-eslint/no-loop-func': 'off',
				// '@typescript-eslint/no-loss-of-precision': 'error',
				// '@typescript-eslint/no-magic-numbers': 'off',
				// '@typescript-eslint/no-meaningless-void-operator': 'error',
				// '@typescript-eslint/no-misused-new': 'error',
				// '@typescript-eslint/no-misused-promises': 'error',
				// '@typescript-eslint/no-mixed-enums': 'error',
				// '@typescript-eslint/no-namespace': 'error',
				// '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
				// '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
				// '@typescript-eslint/no-non-null-assertion': 'error',
				// '@typescript-eslint/no-redeclare': 'off',
				// '@typescript-eslint/no-redundant-type-constituents': 'error',
				// '@typescript-eslint/no-require-imports': 'off',
				// '@typescript-eslint/no-restricted-imports': 'off',
				// '@typescript-eslint/no-shadow': 'off',
				// '@typescript-eslint/no-this-alias': 'error',
				// '@typescript-eslint/no-throw-literal': 'error',
				// '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
				// '@typescript-eslint/no-unnecessary-condition': 'error',
				// '@typescript-eslint/no-unnecessary-qualifier': 'off',
				// '@typescript-eslint/no-unnecessary-type-arguments': 'error',
				// '@typescript-eslint/no-unnecessary-type-assertion': 'error',
				// '@typescript-eslint/no-unnecessary-type-constraint': 'error',
				// '@typescript-eslint/no-unsafe-argument': 'error',
				// '@typescript-eslint/no-unsafe-assignment': 'error',
				// '@typescript-eslint/no-unsafe-call': 'error',
				// '@typescript-eslint/no-unsafe-declaration-merging': 'error',
				// '@typescript-eslint/no-unsafe-enum-comparison': 'error',
				// '@typescript-eslint/no-unsafe-member-access': 'error',
				// '@typescript-eslint/no-unsafe-return': 'error',
				// '@typescript-eslint/no-unsafe-unary-minus': 'off',
				// '@typescript-eslint/no-unused-expressions': 'off',
				// '@typescript-eslint/no-unused-vars': 'error',
				// '@typescript-eslint/no-use-before-define': 'off',
				// '@typescript-eslint/no-useless-constructor': 'error',
				// '@typescript-eslint/no-useless-empty-export': 'off',
				// '@typescript-eslint/no-useless-template-literals': 'error',
				// '@typescript-eslint/no-var-requires': 'error',
				// '@typescript-eslint/non-nullable-type-assertion-style': 'off',
				// '@typescript-eslint/parameter-properties': 'off',
				// '@typescript-eslint/prefer-as-const': 'error',
				// '@typescript-eslint/prefer-destructuring': 'off',
				// '@typescript-eslint/prefer-enum-initializers': 'off',
				// '@typescript-eslint/prefer-for-of': 'off',
				// '@typescript-eslint/prefer-function-type': 'off',
				// '@typescript-eslint/prefer-includes': 'error',
				// '@typescript-eslint/prefer-literal-enum-member': 'error',
				// '@typescript-eslint/prefer-namespace-keyword': 'off',
				// '@typescript-eslint/prefer-nullish-coalescing': 'off',
				// '@typescript-eslint/prefer-optional-chain': 'off',
				// '@typescript-eslint/prefer-readonly': 'off',
				// '@typescript-eslint/prefer-readonly-parameter-types': 'off',
				// '@typescript-eslint/prefer-reduce-type-parameter': 'error',
				// '@typescript-eslint/prefer-regexp-exec': 'off',
				// '@typescript-eslint/prefer-return-this-type': 'error',
				// '@typescript-eslint/prefer-string-starts-ends-with': 'off',
				// '@typescript-eslint/prefer-ts-expect-error': 'error',
				// '@typescript-eslint/promise-function-async': 'off',
				// '@typescript-eslint/require-array-sort-compare': 'off',
				// '@typescript-eslint/require-await': 'error',
				// '@typescript-eslint/restrict-plus-operands': 'error',
				// '@typescript-eslint/restrict-template-expressions': 'error',
				// '@typescript-eslint/return-await': 'off',
				// '@typescript-eslint/sort-type-constituents': 'off',
				// '@typescript-eslint/strict-boolean-expressions': 'off',
				// '@typescript-eslint/switch-exhaustiveness-check': 'off',
				// '@typescript-eslint/triple-slash-reference': 'error',
				// '@typescript-eslint/typedef': 'off',
				// '@typescript-eslint/unbound-method': 'error',
				// '@typescript-eslint/unified-signatures': 'error',
			},
		},
	],
};
