// https://stylelint.io
module.exports = {
	rules: {
		'no-descending-specificity': true,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'font-family-no-duplicate-names': true,
		'keyframe-block-no-duplicate-selectors': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'block-no-empty': true,
		'comment-no-empty': true,
		'no-empty-source': true,
		'color-no-invalid-hex': true,
		'function-calc-no-unspaced-operator': true,
		'keyframe-declaration-no-important': true,
		'media-query-no-invalid': true,
		'named-grid-areas-no-invalid': true,
		'no-invalid-double-slash-comments': true,
		'no-invalid-position-at-import-rule': true,
		'string-no-newline': true,
		'no-irregular-whitespace': true,
		'custom-property-no-missing-var-function': true,
		'font-family-no-missing-generic-family-keyword': true,
		'function-linear-gradient-no-nonstandard-direction': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'selector-anb-no-unmatchable': true,
		'annotation-no-unknown': [true, { severity: 'error' }],
		'at-rule-no-unknown': [
			true,
			{
				severity: 'error',
				ignoreAtRules: ['value'],
			},
		],
		'declaration-property-value-no-unknown': [
			true,
			{
				severity: 'error',
				ignoreProperties: { '/.+/': ['/v-bind/', '/\\$/', '/color-mix/'] },
			},
		],
		'function-no-unknown': [
			true,
			{
				severity: 'error',
				ignoreFunctions: ['global', 'v-bind'],
			},
		],
		'media-feature-name-no-unknown': [true, { severity: 'error' }],
		'media-feature-name-value-no-unknown': [true, { severity: 'error' }],
		'no-unknown-animations': [true, { severity: 'error' }],
		'no-unknown-custom-properties': null,
		'property-no-unknown': [
			true,
			{
				severity: 'error',
				ignoreProperties: ['composes', 'compose-with'],
				ignoreSelectors: [':export', /^:import/],
			},
		],
		'selector-pseudo-class-no-unknown': [
			true,
			{
				severity: 'error',
				ignorePseudoClasses: ['export', 'import', 'global', 'local', 'external', 'deep', 'slotted'],
			},
		],
		'selector-pseudo-element-no-unknown': [
			true,
			{
				severity: 'error',
				ignorePseudoElements: ['v-deep', 'v-global', 'v-slotted'],
			},
		],
		'selector-type-no-unknown': [true, { severity: 'error', ignoreTypes: ['from'] }],
		'unit-no-unknown': [true, { severity: 'error' }],
		'at-rule-allowed-list': null,
		'at-rule-disallowed-list': null,
		'at-rule-no-vendor-prefix': true,
		'at-rule-property-required-list': null,
		'color-hex-alpha': 'never',
		'color-named': 'never',
		'color-no-hex': null,
		'comment-word-disallowed-list': null,
		'declaration-no-important': null,
		'declaration-property-unit-allowed-list': null,
		'declaration-property-unit-disallowed-list': null,
		'declaration-property-value-allowed-list': null,
		'declaration-property-value-disallowed-list': null,
		'function-allowed-list': null,
		'function-disallowed-list': null,
		'function-url-no-scheme-relative': true,
		'function-url-scheme-allowed-list': null,
		'function-url-scheme-disallowed-list': null,
		'length-zero-no-unit': null,
		'media-feature-name-allowed-list': null,
		'media-feature-name-disallowed-list': null,
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-name-unit-allowed-list': null,
		'media-feature-name-value-allowed-list': null,
		'property-allowed-list': null,
		'property-disallowed-list': null,
		'property-no-vendor-prefix': true,
		'rule-selector-property-disallowed-list': null,
		'selector-attribute-name-disallowed-list': null,
		'selector-attribute-operator-allowed-list': null,
		'selector-attribute-operator-disallowed-list': null,
		'selector-combinator-allowed-list': null,
		'selector-combinator-disallowed-list': null,
		'selector-disallowed-list': null,
		'selector-no-qualifying-type': null,
		'selector-no-vendor-prefix': true,
		'selector-pseudo-class-allowed-list': null,
		'selector-pseudo-class-disallowed-list': ['hover'],
		'selector-pseudo-element-allowed-list': null,
		'selector-pseudo-element-disallowed-list': null,
		'unit-allowed-list': null,
		'unit-disallowed-list': null,
		'value-no-vendor-prefix': true,
		'function-name-case': 'lower',
		'selector-type-case': 'lower',
		'value-keyword-case': [
			'lower',
			{
				ignoreFunctions: ['v-bind'],
				camelCaseSvgKeywords: true,
			},
		],
		'at-rule-empty-line-before': [
			'always',
			{
				except: ['first-nested', 'blockless-after-blockless'],
				ignore: ['after-comment'],
				ignoreAtRules: ['else'],
			},
		],
		'comment-empty-line-before': null,
		'custom-property-empty-line-before': [
			'always',
			{
				except: ['first-nested', 'after-custom-property'],
				ignore: ['after-comment'],
			},
		],
		'declaration-empty-line-before': [
			'always',
			{
				except: ['after-declaration', 'first-nested'],
				ignore: ['after-comment'],
			},
		],
		'rule-empty-line-before': [
			'always',
			{
				except: ['first-nested'],
				ignore: ['after-comment'],
			},
		],
		'declaration-block-single-line-max-declarations': null,
		'declaration-property-max-values': null,
		'max-nesting-depth': null,
		'number-max-precision': null,
		'selector-max-attribute': null,
		'selector-max-class': null,
		'selector-max-combinators': null,
		'selector-max-compound-selectors': null,
		'selector-max-id': null,
		'selector-max-pseudo-class': null,
		'selector-max-specificity': null,
		'selector-max-type': null,
		'selector-max-universal': null,
		'time-min-milliseconds': null,
		'alpha-value-notation': 'number',
		'color-function-notation': 'modern',
		'color-hex-length': 'short',
		'font-weight-notation': 'numeric',
		'hue-degree-notation': 'angle',
		'import-notation': 'string',
		'keyframe-selector-notation': 'percentage-unless-within-keyword-only-block',
		'media-feature-range-notation': 'context',
		'selector-not-notation': 'complex',
		'selector-pseudo-element-colon-notation': 'double',
		'comment-pattern': null,
		'custom-media-pattern': null,
		'custom-property-pattern': null,
		'keyframes-name-pattern': null,
		'selector-class-pattern': null,
		'selector-id-pattern': null,
		'selector-nested-pattern': null,
		'font-family-name-quotes': 'always-unless-keyword',
		'function-url-quotes': 'always',
		'selector-attribute-quotes': 'always',
		'declaration-block-no-redundant-longhand-properties': true,
		'shorthand-property-no-redundant-values': true,
		'comment-whitespace-inside': null,
	},
};
