// https://github.com/stylelint-scss/stylelint-scss
module.exports = {
	overrides: [
		{
			files: ['**/*.scss', '**/*.vue'],
			customSyntax: 'postcss-scss',
			plugins: ['stylelint-scss'],
			rules: {
				'media-query-no-invalid': null,
				'scss/at-each-key-value-single-line': true,
				'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
				'scss/at-else-closing-brace-space-after': 'always-intermediate',
				'scss/at-else-empty-line-before': 'never',
				'scss/at-else-if-parentheses-space-before': 'always',
				'scss/at-extend-no-missing-placeholder': true,
				'scss/at-function-named-arguments': null,
				'scss/at-function-parentheses-space-before': 'never',
				'scss/at-function-pattern': null,
				'scss/at-if-closing-brace-newline-after': 'always-last-in-chain',
				'scss/at-if-closing-brace-space-after': 'always-intermediate',
				'scss/at-if-no-null': true,
				'scss/at-import-partial-extension': null,
				'scss/at-import-partial-extension-blacklist': null,
				'scss/at-import-partial-extension-whitelist': null,
				'scss/at-mixin-argumentless-call-parentheses': 'never',
				'scss/at-mixin-named-arguments': null,
				'scss/at-mixin-parentheses-space-before': 'never',
				'scss/at-mixin-pattern': null,
				'scss/at-rule-conditional-no-parentheses': true,
				'at-rule-no-unknown': null,
				'scss/at-rule-no-unknown': [true, { ignoreAtRules: ['value'] }],
				'scss/at-use-no-unnamespaced': true,
				'scss/at-use-no-redundant-alias': true,
				'scss/dollar-variable-colon-newline-after': null,
				'scss/dollar-variable-colon-space-after': 'always',
				'scss/dollar-variable-colon-space-before': 'never',
				'scss/dollar-variable-default': null,
				'scss/dollar-variable-empty-line-after': null,
				'scss/dollar-variable-empty-line-before': [
					'always',
					{
						except: ['first-nested'],
						ignore: ['after-comment', 'after-dollar-variable'],
					},
				],
				'scss/dollar-variable-first-in-block': null,
				'scss/dollar-variable-no-missing-interpolation': true,
				'scss/dollar-variable-no-namespaced-assignment': true,
				'scss/dollar-variable-pattern': null,
				'scss/percent-placeholder-pattern': null,
				'scss/double-slash-comment-empty-line-before': null,
				'scss/double-slash-comment-inline': null,
				'scss/double-slash-comment-whitespace-inside': null,
				'scss/block-no-redundant-nesting': null,
				'comment-no-empty': null,
				'scss/comment-no-empty': true,
				'scss/comment-no-loud': null,
				'scss/declaration-nested-properties': 'never',
				'scss/declaration-nested-properties-no-divided-groups': true,
				'scss/dimension-no-non-numeric-values': true,
				'scss/function-calculation-no-interpolation': true,
				'scss/function-color-relative': null,
				'scss/function-disallowed-list': null,
				'function-no-unknown': null,
				'scss/function-no-unknown': [true, { ignoreFunctions: ['global', 'v-bind'] }],
				'scss/function-quote-no-quoted-strings-inside': null,
				'scss/function-unquote-no-unquoted-strings-inside': null,
				'scss/map-keys-quotes': 'always',
				'scss/media-feature-value-dollar-variable': null,
				'scss/operator-no-newline-after': true,
				'scss/operator-no-newline-before': true,
				'scss/operator-no-unspaced': true,
				'scss/partial-no-import': null,
				'property-no-unknown': null,
				'scss/property-no-unknown': [
					true,
					{
						ignoreProperties: ['composes', 'compose-with'],
						ignoreSelectors: [':export', /^:import/],
					},
				],
				'scss/selector-nest-combinators': null,
				'scss/selector-no-redundant-nesting-selector': null,
				'scss/selector-no-union-class-name': true,
				'scss/load-no-partial-leading-underscore': null,
				'scss/no-dollar-variables': null,
				'scss/no-duplicate-dollar-variables': null,
				'scss/no-duplicate-mixins': true,
				'scss/no-global-function-names': true,
			},
		},
	],
};
